### PR TITLE
Stage 3 proposals which are not ready to ship

### PR DESCRIPTION
**Pull request by littledan**
The proposals repository should document which Stage 3 proposals are not ready to ship; this text documents how that would work. Follow-up on discussion in https://github.com/tc39/Reflector/issues/451. Thanks to @ljharb @syg and @ptomato for helpful feedback in this text.

### CODE REVIEW

**Comment by ljharb** [comment]
btw can you remove the usernames from the commit message? otherwise any time the repo is forked we'll all get a notification ping

**Comment by littledan** [comment]
Good point, sorry about that, fixed.

**Comment by littledan** [comment]
In the TC39 meeting, @codehag suggested that we change "not ready to ship" with "requires implementer coordination", to avoid the implication that features without the tag *are* ready to ship (where in reality engines make case-by-case decisions on Stage 3 proposals). Honestly I'm not really excited about the subsequent wording avoiding shipping, because it makes it somewhat unclear what we're talking about (the goal remains, avoiding shipping things too soon--what else are we coordinating on?). But anyway I'd be fine with landing this in its new state, if people review it.

**Comment by littledan** [comment]
Closing in favor of https://github.com/tc39/how-we-work/pull/130

**Pull request closed without merging**
