### PR TITLE
📝 add pointers on presentation materials

### PR DESCRIPTION
**Pull request by ctcpip**

### CODE REVIEW

**Comment by bakkot** [comment]
I like the spirit of this guidance, but "Always seek permission from proposal authors before redistributing or modifying any presentation materials" feels too strong to me: I've regularly linked people to a slide in a presentation to explain some detail or design question of a proposal, and I don't think it makes sense to have to ask permission before doing this (for presentations which are linked publicly already).

**Comment by ctcpip** [comment]
>  I've regularly linked people to a slide in a presentation to explain some detail or design question of a proposal, and I don't think it makes sense to have to ask permission before doing this (for presentations which are linked publicly already).

It was not intended for this to include something like 'linking to a slide'.  It's meant to include reproducing the slides somewhere, not linking to them.  Do you have any thoughts on how to draw that distinction more clearly?

**Review by littledan — APPROVED** [review]
This is great advice, thank you for writing it up!

**Comment by littledan** [comment]
@bakkot does the current text resolve your concerns?

**Comment by bakkot** [comment]
Yeah, seems fine now. Only quibble is that I'm not sure it makes all that much sense to distinguish between "posting" and "linking" materials, but since it explicitly says linking is fine I'm not too worried.

**Pull request merged**
