### PR TITLE
💬 update how to host page

### PR DESCRIPTION
**Pull request by ctcpip**
updated this doc for accuracy w/ current process.  please point out any problems or corrections

not a blocker, but it would be a good idea to expand on the teleconference item a little more, re: making sure the room is mic'ed properly / has a good and reliable means of capturing dialogue from attendees for the teleconferencing

### CODE REVIEW

**Comment by ctcpip** [comment]
NB: the removal of `whiteboards and markers` requirement

**Review by ljharb — APPROVED** [review]
why no whiteboards? it’s useful during breaks and for local-only info

**Comment by ctcpip** [comment]
> why no whiteboards? it’s useful during breaks and for local-only info

good call -- I wasn't sure about that change, which was the reason for the NB.  will bring it back

**Review by robpalme — APPROVED** [review]
Thanks for improving this.

**Comment by ctcpip** [comment]
just pushed a change to correct the number of meetings per year (`line 3`)

**Pull request merged**
